Repository carbon-design-system/carbon-web-components, pull requests merged in 2021-10, with the labels that each got.

#703 fix(radio-button): apply `disabled` prop to input
  src/components/radio-button/radio-button.ts
  tests/snapshots/bx-radio-button.md
Labels: Ready to merge, hacktoberfest-accepted

#706 docs(data-table): updating `sort-direction` docs
  src/components/data-table/table-header-cell.ts
Labels: Ready to merge, dev

#709 chore(release): bump to version 1.17.0
  package.json
Labels: Ready to merge, dev

#724 fix(deploy): fix to properly tag the repo after publish
  .github/workflows/deploy.yml
  .github/workflows/publish.yml
Labels: Ready to merge, dev, hacktoberfest-accepted
