Repository carbon-design-system/carbon-web-components, pull requests merged in 2021-04, with the labels that each got.

#615 chore(dependencies): upgrade `sass-loader`
  .storybook/main.js
  .yarn/offline-mirror/buffer-json-2.0.0.tgz
  .yarn/offline-mirror/cache-loader-4.1.0.tgz
  .yarn/offline-mirror/camelcase-6.2.0.tgz
  .yarn/offline-mirror/cli-source-preview-1.1.0.tgz
  .yarn/offline-mirror/clone-deep-2.0.2.tgz
  .yarn/offline-mirror/colorette-1.2.2.tgz
  .yarn/offline-mirror/css-loader-2.0.2.tgz
  .yarn/offline-mirror/css-loader-5.2.0.tgz
  .yarn/offline-mirror/env-paths-2.2.1.tgz
  .yarn/offline-mirror/fast-sass-loader-1.5.0.tgz
  .yarn/offline-mirror/fs-extra-3.0.1.tgz
  .yarn/offline-mirror/graceful-fs-4.2.6.tgz
  .yarn/offline-mirror/icss-utils-5.1.0.tgz
  .yarn/offline-mirror/jsonfile-3.0.1.tgz
  .yarn/offline-mirror/lodash.tail-4.1.1.tgz
  .yarn/offline-mirror/nanoid-3.1.22.tgz
  .yarn/offline-mirror/node-gyp-7.1.2.tgz
  .yarn/offline-mirror/node-sass-4.13.0.tgz
  .yarn/offline-mirror/node-sass-5.0.0.tgz
  .yarn/offline-mirror/nopt-5.0.0.tgz
  .yarn/offline-mirror/postcss-8.2.9.tgz
  .yarn/offline-mirror/postcss-modules-extract-imports-3.0.0.tgz
  .yarn/offline-mirror/postcss-modules-local-by-default-2.0.3.tgz
  .yarn/offline-mirror/postcss-modules-local-by-default-4.0.0.tgz
  .yarn/offline-mirror/postcss-modules-scope-2.0.1.tgz
  .yarn/offline-mirror/postcss-modules-scope-3.0.0.tgz
  .yarn/offline-mirror/postcss-modules-values-2.0.0.tgz
  .yarn/offline-mirror/postcss-modules-values-4.0.0.tgz
  .yarn/offline-mirror/postcss-selector-parser-6.0.4.tgz
  .yarn/offline-mirror/sass-graph-2.2.5.tgz
  .yarn/offline-mirror/sass-loader-7.1.0.tgz
  .yarn/offline-mirror/shallow-clone-1.0.0.tgz
  .yarn/offline-mirror/style-loader-0.23.1.tgz
  .yarn/offline-mirror/style-loader-2.0.0.tgz
  package.json
  tests/karma.conf.js
  yarn.lock
Labels: Ready to merge, package: carbon web components

#618 docs(readme): misc update
  docs/form-story.mdx
  docs/welcome-story.mdx
Labels: package: carbon web components

#616 docs(readme): misc updates
  README.md
  docs/welcome-story-angular.mdx
  docs/welcome-story.mdx
Labels: Ready to merge, package: carbon web components

#613 feat(modal): support one/three buttons
  src/components/button/button.scss
  src/components/modal/modal-footer-button.ts
  src/components/modal/modal-footer.ts
  src/components/modal/modal-story-angular.ts
  src/components/modal/modal-story-react.tsx
  src/components/modal/modal-story-vue.ts
  src/components/modal/modal-story.mdx
  src/components/modal/modal-story.ts
  src/components/modal/modal.scss
Labels: Ready to merge, package: carbon web components

#621 docs(welcome): updating content regarding framework wrappers
  docs/welcome-story.mdx
Labels: Ready to merge

#623 docs(readme): updates on JavaScript framework support
  README.md
  docs/welcome-story.mdx
Labels: Ready to merge, package: carbon web components

#625 docs(readme): another in sync with Carbon website
  README.md
  docs/welcome-story.mdx
Labels: package: carbon web components

#624 fix(combo-box): make X button clear the selection
  src/components/combo-box/combo-box.ts
  tests/karma-setup-renderroot.js
  tests/karma.conf.js
  tests/spec/combo-box_spec.ts
Labels: Ready to merge, package: carbon web components
