Repository carbon-design-system/carbon-web-components, pull requests merged in 2021-11, with the labels that each got.

#725 fix(github-actions): switched percy update to use ubuntu latest
  .github/workflows/percy-update-base.yml
Labels: Ready to merge, dev

#729 chore: update checkout and setup-node actions
  .github/workflows/ci-check.yml
  .github/workflows/deploy.yml
  .github/workflows/percy-update-base.yml
  .github/workflows/publish.yml
  .github/workflows/reviewdog.yml
Labels: Ready to merge

#735 chore(eslint): disable lint warnings
  examples/codesandbox/angular/src/main.ts
  examples/codesandbox/form/angular/src/app/app.component.ts
  examples/codesandbox/form/angular/src/main.ts
  tools/get-changelog.js
Labels: Ready to merge

#734 chore: setup actions/setup-node@v2 cache
  .github/workflows/ci-check.yml
  .github/workflows/deploy.yml
  .github/workflows/percy-update-base.yml
  .github/workflows/publish.yml
  .github/workflows/reviewdog.yml
Labels: Ready to merge

#742 docs(welcome): update getting started install section
  docs/welcome-story.mdx
Labels: Ready to merge

#740 chore(dependencies): update typescript
  package.json
  yarn.lock
Labels: Ready to merge

#744 chore: prevents actions from forks
  .github/workflows/percy-update-base.yml
  .github/workflows/publish.yml
Labels: Ready to merge

#745 chore(lit): update lit dependencies
  .yarn/offline-mirror/lit-element-2.3.1.tgz
  .yarn/offline-mirror/lit-element-2.5.1.tgz
  .yarn/offline-mirror/lit-html-1.3.0.tgz
  .yarn/offline-mirror/lit-html-1.4.1.tgz
  examples/codesandbox/data-table/package.json
  package.json
  yarn.lock
Labels: Ready to merge

#749 chore(dependencies): update dev dependencies
  .yarn/offline-mirror/@angular-devkit-architect-0.900.2.tgz
  .yarn/offline-mirror/@angular-devkit-architect-0.900.7.tgz
  .yarn/offline-mirror/@angular-devkit-build-angular-0.900.2.tgz
  .yarn/offline-mirror/@angular-devkit-build-angular-0.900.7.tgz
  .yarn/offline-mirror/@angular-devkit-build-optimizer-0.900.2.tgz
  .yarn/offline-mirror/@angular-devkit-build-optimizer-0.900.7.tgz
  .yarn/offline-mirror/@angular-devkit-build-webpack-0.900.2.tgz
  .yarn/offline-mirror/@angular-devkit-build-webpack-0.900.7.tgz
  .yarn/offline-mirror/@angular-devkit-core-9.0.2.tgz
  .yarn/offline-mirror/@angular-devkit-core-9.0.7.tgz
  .yarn/offline-mirror/@angular-forms-8.2.12.tgz
  .yarn/offline-mirror/@angular-forms-8.2.14.tgz
  .yarn/offline-mirror/@ngtools-webpack-9.0.2.tgz
  .yarn/offline-mirror/@ngtools-webpack-9.0.7.tgz
  .yarn/offline-mirror/@types-bluebird-3.5.32.tgz
  .yarn/offline-mirror/@types-bluebird-3.5.36.tgz
  .yarn/offline-mirror/browserslist-4.17.6.tgz
  .yarn/offline-mirror/camelcase-6.2.0.tgz
  .yarn/offline-mirror/caniuse-lite-1.0.30001020.tgz
  .yarn/offline-mirror/caniuse-lite-1.0.30001278.tgz
  .yarn/offline-mirror/core-js-3.1.3.tgz
  .yarn/offline-mirror/core-js-3.19.1.tgz
  .yarn/offline-mirror/core-js-3.6.0.tgz
  .yarn/offline-mirror/core-js-3.6.4.tgz
  .yarn/offline-mirror/cross-env-7.0.2.tgz
  .yarn/offline-mirror/cross-env-7.0.3.tgz
  .yarn/offline-mirror/css-loader-5.2.0.tgz
  .yarn/offline-mirror/css-loader-5.2.7.tgz
  .yarn/offline-mirror/electron-to-chromium-1.3.889.tgz
  .yarn/offline-mirror/es6-promise-4.2.5.tgz
  .yarn/offline-mirror/execa-5.1.1.tgz
  .yarn/offline-mirror/expect-playwright-0.2.6.tgz
  .yarn/offline-mirror/globby-10.0.1.tgz
  .yarn/offline-mirror/globby-10.0.2.tgz
  .yarn/offline-mirror/gulp-clean-css-4.2.0.tgz
  .yarn/offline-mirror/gulp-clean-css-4.3.0.tgz
  .yarn/offline-mirror/nanoid-3.1.30.tgz
  .yarn/offline-mirror/node-releases-2.0.1.tgz
  .yarn/offline-mirror/picocolors-1.0.0.tgz
  .yarn/offline-mirror/postcss-8.3.11.tgz
  .yarn/offline-mirror/source-map-js-0.6.2.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#753 chore(github-actions): improve GA logic
  .github/workflows/percy-update-base.yml
  .github/workflows/publish.yml
Labels: Ready to merge

#758 chore(dependencies): update ^0. deps versions
  .yarn/offline-mirror/@open-wc-semantic-dom-diff-0.15.4.tgz
  .yarn/offline-mirror/@open-wc-semantic-dom-diff-0.18.0.tgz
  .yarn/offline-mirror/@types-chai-4.2.22.tgz
  .yarn/offline-mirror/karma-sourcemap-loader-0.3.7.tgz
  .yarn/offline-mirror/karma-sourcemap-loader-0.3.8.tgz
  .yarn/offline-mirror/temp-0.9.1.tgz
  .yarn/offline-mirror/temp-0.9.4.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#741 chore(dependencies): update sass & sass-loader
  .yarn/offline-mirror/sass-1.39.0.tgz
  .yarn/offline-mirror/sass-1.40.1.tgz
  .yarn/offline-mirror/sass-loader-10.2.0.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#752 chore(carbon): switch to exact dependency for Carbon
  package.json
  yarn.lock
Labels: Ready to merge, dev

#759 chore(github-actions): add concurrency config to github actions
  .github/workflows/ci-check.yml
  .github/workflows/deploy.yml
  .github/workflows/percy-update-base.yml
  .github/workflows/reviewdog.yml
Labels: Ready to merge

#762 chore(dependencies): update commander
  package.json
  yarn.lock
Labels: Ready to merge

#768 chore(dependencies): update vue deps
  .yarn/offline-mirror/@vue-component-compiler-utils-3.0.0.tgz
  .yarn/offline-mirror/@vue-component-compiler-utils-3.3.0.tgz
  .yarn/offline-mirror/acorn-6.0.5.tgz
  .yarn/offline-mirror/acorn-jsx-5.0.1.tgz
  .yarn/offline-mirror/acorn-jsx-5.3.2.tgz
  .yarn/offline-mirror/cssesc-2.0.0.tgz
  .yarn/offline-mirror/eslint-scope-4.0.0.tgz
  .yarn/offline-mirror/espree-5.0.0.tgz
  .yarn/offline-mirror/espree-6.2.1.tgz
  .yarn/offline-mirror/esquery-1.0.1.tgz
  .yarn/offline-mirror/picocolors-0.2.1.tgz
  .yarn/offline-mirror/postcss-7.0.39.tgz
  .yarn/offline-mirror/postcss-selector-parser-5.0.0.tgz
  .yarn/offline-mirror/vue-2.6.10.tgz
  .yarn/offline-mirror/vue-2.6.14.tgz
  .yarn/offline-mirror/vue-eslint-parser-6.0.5.tgz
  .yarn/offline-mirror/vue-eslint-parser-7.11.0.tgz
  .yarn/offline-mirror/vue-loader-15.7.1.tgz
  .yarn/offline-mirror/vue-loader-15.9.8.tgz
  .yarn/offline-mirror/vue-template-compiler-2.6.10.tgz
  .yarn/offline-mirror/vue-template-compiler-2.6.14.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#766 chore(github): add github dependabot configuration
  .github/dependabot.yml
Labels: Ready to merge

#765 chore(dependencies): update yasmine deps
  .yarn/offline-mirror/@types-jasmine-3.10.2.tgz
  .yarn/offline-mirror/@types-jasmine-3.6.4.tgz
  .yarn/offline-mirror/jasmine-core-3.10.1.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#764 chore(dependencies): update babel-runtime
  .yarn/offline-mirror/@babel-runtime-7.12.18.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#763 chore(dependencies): update del
  .yarn/offline-mirror/del-2.2.2.tgz
  .yarn/offline-mirror/globby-5.0.0.tgz
  .yarn/offline-mirror/is-path-cwd-1.0.0.tgz
  .yarn/offline-mirror/is-path-in-cwd-1.0.1.tgz
  .yarn/offline-mirror/is-path-inside-1.0.1.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#716 feat(multi-select): introduce filterable mode
  src/components/multi-select/multi-select-item.ts
  src/components/multi-select/multi-select-story-angular.ts
  src/components/multi-select/multi-select-story-react.tsx
  src/components/multi-select/multi-select-story-vue.ts
  src/components/multi-select/multi-select-story.mdx
  src/components/multi-select/multi-select-story.ts
  src/components/multi-select/multi-select.scss
  src/components/multi-select/multi-select.ts
  tests/spec/multi-select_spec.ts
Labels: Ready to merge

#775 chore(github-actions): add workflow to auto update yarn mirror
  .github/workflows/dependabot-yarn-mirror.yml
Labels: Ready to merge, dev

#781 fix(github-actions): turn back on percy update base
  .github/workflows/dependabot-yarn-mirror.yml
  .github/workflows/percy-update-base.yml
Labels: Ready to merge, dev

#777 chore(dependencies): update babel deps
  .yarn/offline-mirror/@babel-plugin-proposal-class-properties-7.12.13.tgz
  .yarn/offline-mirror/@babel-plugin-proposal-decorators-7.12.13.tgz
  .yarn/offline-mirror/@babel-plugin-proposal-decorators-7.16.0.tgz
  .yarn/offline-mirror/@babel-plugin-proposal-nullish-coalescing-operator-7.12.13.tgz
  .yarn/offline-mirror/@babel-plugin-proposal-object-rest-spread-7.12.13.tgz
  .yarn/offline-mirror/@babel-plugin-proposal-optional-chaining-7.12.17.tgz
  .yarn/offline-mirror/@babel-plugin-syntax-decorators-7.16.0.tgz
  .yarn/offline-mirror/@babel-plugin-transform-template-literals-7.12.13.tgz
  .yarn/offline-mirror/@babel-runtime-7.12.18.tgz
  .yarn/offline-mirror/@babel-runtime-7.16.3.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#796 fix(ci): fix the yarn offline action
  .github/workflows/dependabot-yarn-mirror.yml
Labels: Ready to merge

#789 Revert "chore: make the forks check dynamic (#753)"
  .github/workflows/percy-update-base.yml
  .github/workflows/publish.yml
Labels: Ready to merge

#801 chore(renovate): revert back to default renovate behavior
  renovate.json
Labels: dev

#802 chore(deps): remove lit-html from resolutions
  package.json
  yarn.lock
Labels: Ready to merge

#804 chore(deps): update mini-css-extract-plugin
  .yarn/offline-mirror/mini-css-extract-plugin-0.12.0.tgz
  .yarn/offline-mirror/mini-css-extract-plugin-0.5.0.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#805 chore(deps): update autoprefixer
  .yarn/offline-mirror/autoprefixer-9.4.3.tgz
  .yarn/offline-mirror/autoprefixer-9.8.8.tgz
  .yarn/offline-mirror/browserslist-4.3.6.tgz
  .yarn/offline-mirror/electron-to-chromium-1.3.96.tgz
  .yarn/offline-mirror/node-releases-1.1.2.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#803 chore(deps): update babel deps
  .yarn/offline-mirror/@babel-helper-define-polyfill-provider-0.2.4.tgz
  .yarn/offline-mirror/@babel-plugin-transform-react-display-name-7.16.0.tgz
  .yarn/offline-mirror/@babel-plugin-transform-react-pure-annotations-7.16.0.tgz
  .yarn/offline-mirror/@babel-plugin-transform-runtime-7.12.17.tgz
  .yarn/offline-mirror/@babel-plugin-transform-runtime-7.16.0.tgz
  .yarn/offline-mirror/@babel-preset-react-7.12.13.tgz
  .yarn/offline-mirror/@babel-preset-react-7.16.0.tgz
  .yarn/offline-mirror/@babel-traverse-7.12.17.tgz
  .yarn/offline-mirror/arr-diff-2.0.0.tgz
  .yarn/offline-mirror/array-unique-0.2.1.tgz
  .yarn/offline-mirror/babel-loader-8.2.3.tgz
  .yarn/offline-mirror/babel-plugin-istanbul-4.1.6.tgz
  .yarn/offline-mirror/babel-plugin-polyfill-corejs2-0.2.3.tgz
  .yarn/offline-mirror/babel-plugin-polyfill-corejs3-0.3.0.tgz
  .yarn/offline-mirror/babel-plugin-polyfill-regenerator-0.2.3.tgz
  .yarn/offline-mirror/braces-1.8.5.tgz
  .yarn/offline-mirror/expand-brackets-0.1.5.tgz
  .yarn/offline-mirror/expand-range-1.8.2.tgz
  .yarn/offline-mirror/extglob-0.3.2.tgz
  .yarn/offline-mirror/filename-regex-2.0.1.tgz
  .yarn/offline-mirror/fill-range-2.2.4.tgz
  .yarn/offline-mirror/is-dotfile-1.0.3.tgz
  .yarn/offline-mirror/is-equal-shallow-0.1.3.tgz
  .yarn/offline-mirror/is-number-2.1.0.tgz
  .yarn/offline-mirror/is-posix-bracket-0.1.1.tgz
  .yarn/offline-mirror/is-primitive-2.0.0.tgz
  .yarn/offline-mirror/math-random-1.0.1.tgz
  .yarn/offline-mirror/micromatch-2.3.11.tgz
  .yarn/offline-mirror/object.omit-2.0.1.tgz
  .yarn/offline-mirror/parse-glob-3.0.4.tgz
  .yarn/offline-mirror/preserve-0.2.0.tgz
  .yarn/offline-mirror/randomatic-3.1.1.tgz
  .yarn/offline-mirror/regex-cache-0.4.4.tgz
  .yarn/offline-mirror/test-exclude-4.2.3.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#806 chore(deps): update flatpickr
  package.json
Labels: Ready to merge

#808 chore(deps): update react
  .yarn/offline-mirror/react-16.8.6.tgz
  .yarn/offline-mirror/react-dom-16.8.6.tgz
  .yarn/offline-mirror/scheduler-0.13.6.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#831 chore(deps): downgrade @storybook/angular
  .yarn/offline-mirror/@storybook-addons-6.2.9.tgz
  .yarn/offline-mirror/@storybook-angular-6.2.9.tgz
  .yarn/offline-mirror/@storybook-angular-6.3.12.tgz
  .yarn/offline-mirror/@storybook-api-6.2.9.tgz
  .yarn/offline-mirror/@storybook-builder-webpack4-6.2.9.tgz
  .yarn/offline-mirror/@storybook-channel-postmessage-6.2.9.tgz
  .yarn/offline-mirror/@storybook-channels-6.2.9.tgz
  .yarn/offline-mirror/@storybook-client-api-6.2.9.tgz
  .yarn/offline-mirror/@storybook-client-logger-6.2.9.tgz
  .yarn/offline-mirror/@storybook-components-6.2.9.tgz
  .yarn/offline-mirror/@storybook-core-6.2.9.tgz
  .yarn/offline-mirror/@storybook-core-client-6.2.9.tgz
  .yarn/offline-mirror/@storybook-core-common-6.2.9.tgz
  .yarn/offline-mirror/@storybook-core-events-6.2.9.tgz
  .yarn/offline-mirror/@storybook-core-server-6.2.9.tgz
  .yarn/offline-mirror/@storybook-node-logger-6.2.9.tgz
  .yarn/offline-mirror/@storybook-router-6.2.9.tgz
  .yarn/offline-mirror/@storybook-theming-6.2.9.tgz
  .yarn/offline-mirror/@storybook-ui-6.2.9.tgz
  .yarn/offline-mirror/react-colorful-5.5.1.tgz
  .yarn/offline-mirror/schema-utils-2.7.1.tgz
  .yarn/offline-mirror/terser-webpack-plugin-3.1.0.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#838 chore(ci): update prevent actions
  .github/workflows/percy-update-base.yml
  .github/workflows/publish.yml
Labels: Ready to merge

#816 fix(slider): negative values are now supported
  .github/workflows/reviewdog.yml
  src/components/slider/slider.ts
Labels: Ready to merge

#841 chore(release): bump to v1.19.0
  package.json
Labels: Ready to merge, dev

#891 chore(deps): update `@babel/plugin-transform-typescript`
  .yarn/offline-mirror/@babel-core-7.12.17.tgz
  .yarn/offline-mirror/@babel-plugin-transform-typescript-7.12.17.tgz
  .yarn/offline-mirror/acorn-8.5.0.tgz
  .yarn/offline-mirror/ajv-8.6.3.tgz
  .yarn/offline-mirror/ansi-escapes-4.3.1.tgz
  .yarn/offline-mirror/browserslist-4.17.6.tgz
  .yarn/offline-mirror/caniuse-lite-1.0.30001278.tgz
  .yarn/offline-mirror/chalk-4.1.0.tgz
  .yarn/offline-mirror/convert-source-map-1.7.0.tgz
  .yarn/offline-mirror/electron-to-chromium-1.3.889.tgz
  .yarn/offline-mirror/extract-zip-2.0.0.tgz
  .yarn/offline-mirror/find-process-1.4.3.tgz
  .yarn/offline-mirror/follow-redirects-1.5.10.tgz
  .yarn/offline-mirror/get-stream-6.0.0.tgz
  .yarn/offline-mirror/indexes-of-1.0.1.tgz
  .yarn/offline-mirror/istanbul-lib-instrument-4.0.1.tgz
  .yarn/offline-mirror/node-fetch-2.6.1.tgz
  .yarn/offline-mirror/open-7.1.0.tgz
  .yarn/offline-mirror/parse-node-version-1.0.0.tgz
  .yarn/offline-mirror/postcss-selector-parser-6.0.4.tgz
  .yarn/offline-mirror/psl-1.7.0.tgz
  .yarn/offline-mirror/react-colorful-5.5.0.tgz
  .yarn/offline-mirror/rxjs-6.5.3.tgz
  .yarn/offline-mirror/schema-utils-3.0.0.tgz
  .yarn/offline-mirror/semver-5.6.0.tgz
  .yarn/offline-mirror/signal-exit-3.0.3.tgz
  .yarn/offline-mirror/terser-5.9.0.tgz
  .yarn/offline-mirror/type-fest-0.11.0.tgz
  .yarn/offline-mirror/uniq-1.0.1.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#893 fix: remove duplicated `bx-loading`
  src/typings/jsx-elements.d.ts
Labels: Ready to merge

#743 chore(codesandbox): clean the codesandbox deps
  examples/codesandbox/angular/package.json
  examples/codesandbox/basic/package.json
  examples/codesandbox/data-table/package.json
  examples/codesandbox/form/angular/package.json
  examples/codesandbox/form/basic/package.json
  examples/codesandbox/form/redux-form/package.json
  examples/codesandbox/ie/package.json
  examples/codesandbox/next/package.json
  examples/codesandbox/react-ssr/package.json
  examples/codesandbox/react/package.json
  examples/codesandbox/rtl/package.json
  examples/codesandbox/styling/custom-style/package.json
  examples/codesandbox/styling/theme-zoning/package.json
  examples/codesandbox/vue/package.json
Labels: Ready to merge

#894 chore: remove custom skipLibCheck
  src/typings/resources.d.ts
  src/typings/vendor.d.ts
  tsconfig-angular-esm2015.json
  tsconfig.json
Labels: Ready to merge

#899 chore(deps): install prettier-plugin-package
  .prettierignore
  .yarn/offline-mirror/prettier-plugin-package-1.3.0.tgz
  examples/codesandbox/angular/package.json
  examples/codesandbox/angular/tsconfig.app.json
  examples/codesandbox/angular/tsconfig.json
  examples/codesandbox/cdn/package.json
  examples/codesandbox/data-table/package.json
  examples/codesandbox/form/angular/package.json
  examples/codesandbox/form/angular/tsconfig.app.json
  examples/codesandbox/form/angular/tsconfig.json
  examples/codesandbox/ie/package.json
  examples/codesandbox/next/package.json
  examples/codesandbox/rtl/package.json
  examples/codesandbox/vue/package.json
  package.json
  renovate.json
  tsconfig.json
  yarn.lock
Labels: Ready to merge
