Repository carbon-design-system/carbon-web-components, pull requests merged in 2022-02, with the labels that each got.

#934 docs: update sandbox example link
  examples/codesandbox/styling/theme-zoning/index.html
Labels: Ready to merge

#924 fix(drop-container): clear input value on change
  src/components/file-uploader/drop-container.ts
Labels: Ready to merge

#941 chore(release): bump to v1.21.0
  .github/workflows/dependabot-yarn-mirror.yml
  .github/workflows/publish.yml
  package.json
Labels: Ready to merge, dev

#942 docs(input): fix input type knob
  src/components/input/stories/helpers.ts
Labels: Ready to merge, storybook

#948 feat(breadcrumb): introduce overflow menu
  src/components/breadcrumb/breadcrumb-overflow-menu.ts
  src/components/breadcrumb/breadcrumb-story-angular.ts
  src/components/breadcrumb/breadcrumb-story-react.tsx
  src/components/breadcrumb/breadcrumb-story-vue.ts
  src/components/breadcrumb/breadcrumb-story.mdx
  src/components/breadcrumb/breadcrumb-story.ts
  src/components/breadcrumb/breadcrumb.scss
  src/components/overflow-menu/overflow-menu.scss
Labels: Ready to merge

#957 chore(ci): add git clean to remove angular artifacts
  .prettierignore
  tools/deploy.sh
Labels: Ready to merge

#960 chore(deps): downgrade `karma-webpack` to v4
  .yarn/offline-mirror/karma-webpack-4.0.2.tgz
  .yarn/offline-mirror/karma-webpack-5.0.0.tgz
  .yarn/offline-mirror/webpack-merge-4.2.2.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#964 fix(jest): downgrade to v26
  .yarn/offline-mirror/@jest-console-27.3.1.tgz
  .yarn/offline-mirror/@jest-core-26.6.3.tgz
  .yarn/offline-mirror/@jest-core-27.3.1.tgz
  .yarn/offline-mirror/@jest-globals-27.3.1.tgz
  .yarn/offline-mirror/@jest-reporters-26.6.2.tgz
  .yarn/offline-mirror/@jest-reporters-27.3.1.tgz
  .yarn/offline-mirror/@jest-source-map-27.0.6.tgz
  .yarn/offline-mirror/@jest-test-result-27.3.1.tgz
  .yarn/offline-mirror/@jest-test-sequencer-27.3.1.tgz
  .yarn/offline-mirror/@jest-transform-27.3.1.tgz
  .yarn/offline-mirror/babel-jest-27.3.1.tgz
  .yarn/offline-mirror/babel-plugin-jest-hoist-27.2.0.tgz
  .yarn/offline-mirror/babel-preset-jest-27.2.0.tgz
  .yarn/offline-mirror/cjs-module-lexer-1.2.2.tgz
  .yarn/offline-mirror/diff-sequences-27.0.6.tgz
  .yarn/offline-mirror/emittery-0.8.1.tgz
  .yarn/offline-mirror/execa-4.1.0.tgz
  .yarn/offline-mirror/expect-27.3.1.tgz
  .yarn/offline-mirror/growly-1.3.0.tgz
  .yarn/offline-mirror/human-signals-1.1.1.tgz
  .yarn/offline-mirror/jest-26.6.3.tgz
  .yarn/offline-mirror/jest-27.3.1.tgz
  .yarn/offline-mirror/jest-changed-files-26.6.2.tgz
  .yarn/offline-mirror/jest-changed-files-27.3.0.tgz
  .yarn/offline-mirror/jest-circus-27.3.1.tgz
  .yarn/offline-mirror/jest-cli-26.6.3.tgz
  .yarn/offline-mirror/jest-cli-27.3.1.tgz
  .yarn/offline-mirror/jest-config-27.3.1.tgz
  .yarn/offline-mirror/jest-diff-27.3.1.tgz
  .yarn/offline-mirror/jest-docblock-27.0.6.tgz
  .yarn/offline-mirror/jest-each-27.3.1.tgz
  .yarn/offline-mirror/jest-environment-jsdom-27.3.1.tgz
  .yarn/offline-mirror/jest-get-type-27.3.1.tgz
  .yarn/offline-mirror/jest-haste-map-27.3.1.tgz
  .yarn/offline-mirror/jest-jasmine2-27.3.1.tgz
  .yarn/offline-mirror/jest-leak-detector-27.3.1.tgz
  .yarn/offline-mirror/jest-matcher-utils-27.3.1.tgz
  .yarn/offline-mirror/jest-regex-util-27.0.6.tgz
  .yarn/offline-mirror/jest-resolve-27.3.1.tgz
  .yarn/offline-mirror/jest-resolve-dependencies-26.6.3.tgz
  .yarn/offline-mirror/jest-resolve-dependencies-27.3.1.tgz
  .yarn/offline-mirror/jest-runner-27.3.1.tgz
  .yarn/offline-mirror/jest-runtime-27.3.1.tgz
  .yarn/offline-mirror/jest-serializer-27.0.6.tgz
  .yarn/offline-mirror/jest-snapshot-27.3.1.tgz
  .yarn/offline-mirror/jest-validate-27.3.1.tgz
  .yarn/offline-mirror/jest-watcher-26.6.2.tgz
  .yarn/offline-mirror/jest-watcher-27.3.1.tgz
  .yarn/offline-mirror/node-notifier-8.0.2.tgz
  .yarn/offline-mirror/p-each-series-2.2.0.tgz
  .yarn/offline-mirror/resolve.exports-1.1.0.tgz
  .yarn/offline-mirror/shellwords-0.1.1.tgz
  .yarn/offline-mirror/throat-6.0.1.tgz
  .yarn/offline-mirror/uuid-8.3.2.tgz
  .yarn/offline-mirror/v8-to-istanbul-7.1.2.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#965 chore: remove deprecation warnings and add snapshot update script
  gulp-tasks/build/modules/css.js
  gulp-tasks/test.js
  package.json
  tests/karma.conf.js
  tests/utils/snapshot.js
Labels: Ready to merge, dev, housekeeping

#962 chore(deps): downgrade `execa` to v5
  .yarn/offline-mirror/cookie-0.4.1.tgz
  .yarn/offline-mirror/eslint-visitor-keys-1.0.0.tgz
  .yarn/offline-mirror/execa-6.0.0.tgz
  .yarn/offline-mirror/human-signals-3.0.1.tgz
  .yarn/offline-mirror/is-stream-3.0.0.tgz
  .yarn/offline-mirror/karma-webpack-4.0.2.tgz
  .yarn/offline-mirror/mimic-fn-4.0.0.tgz
  .yarn/offline-mirror/npm-run-path-5.0.1.tgz
  .yarn/offline-mirror/onetime-6.0.0.tgz
  .yarn/offline-mirror/path-key-4.0.0.tgz
  .yarn/offline-mirror/qs-6.9.7.tgz
  .yarn/offline-mirror/strip-final-newline-3.0.0.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#947 feat(input): implement password input
  src/components/input/defs.ts
  src/components/input/input-story.ts
  src/components/input/input.scss
  src/components/input/input.ts
  src/components/input/stories/helpers.ts
  tests/snapshots/bx-number-input.md
  tests/snapshots/bx-select.md
  tests/spec/input_spec.ts
Labels: Ready to merge

#959 fix(input): add aria-describedby for helper text
  src/components/input/input.ts
  tests/snapshots/bx-input.md
Labels: Ready to merge

#958 chore(deps): update autoprefixer browserslist options
  .storybook/main.js
  gulp-tasks/build/modules/css.js
  package.json
  tools/get-rollup-config.js
Labels: Ready to merge

#940 feat(tooltip): implement alignment prop
  src/components/tooltip/tooltip-body.ts
  src/components/tooltip/tooltip-story.scss
  src/components/tooltip/tooltip-story.ts
  src/components/tooltip/tooltip.scss
Labels: Ready to merge

#967 feat(search): adds `formdata` event handling
  src/components/search/search.ts
Labels: Ready to merge
