Repository carbon-design-system/carbon-web-components, pull requests merged in 2022-01, with the labels that each got.

#919 docs(file-uploader): correct file uploader events documentation
  src/components/file-uploader/file-uploader-item.ts
Labels: Ready to merge

#914 fix(slider): fix slider usability on touch devices
  src/components/slider/slider.ts
Labels: Ready to merge

#920 docs(cdn): remove reference to next tag
  src/globals/internal/storybook-cdn.ts
Labels: Ready to merge, dev, documentation

#923 chore(support): add assignees for issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/question.yaml
  .github/ISSUE_TEMPLATE/user_story.yaml
Labels: Ready to merge, dev

#925 docs(data-table): add variations to codesandbox example
  examples/codesandbox/basic/components/data-table/cdn.html
  examples/codesandbox/basic/components/data-table/data.js
  examples/codesandbox/basic/components/data-table/defs.js
  examples/codesandbox/basic/components/data-table/index.html
  examples/codesandbox/basic/components/data-table/sortable-pagination.js
  examples/codesandbox/basic/components/data-table/sortable-table.js
  examples/codesandbox/basic/components/data-table/src/index.js
  src/components/data-table/data-table-story.mdx
Labels: Ready to merge, documentation
